import 'dart:convert';
import 'dart:io';

import 'package:alluvial_domain/alluvial_domain.dart';
import 'package:alluvial_render/alluvial_render.dart';
import 'package:alluvial_store_yaml/alluvial_store_yaml.dart';
import 'package:shouldly/shouldly.dart';
import 'package:test/test.dart';

/// The port's real gate: byte-identity with the Python engine that produced
/// every approved chart.
///
/// The corpus is generated by the Python pipeline — see
/// `dart/tool/render_reference.py`: for each braid film the page's own embed
/// (default, colour-blind, mini) and the spec dict as JSON, plus every
/// two-clock chart. When the corpus is absent the test SKIPS — it is a gate,
/// not a fixture, and a port cannot invent its own reference.
final _store = Platform.environment['ALLUVIAL_STORE'] ?? '../../../films';
final _reference = Platform.environment['ALLUVIAL_REFERENCE'] ?? '/tmp/ref';

Future<void> main() async {
  final corpusThere = Directory(_reference).existsSync();
  final storeThere = Directory(_store).existsSync();

  group('byte-identity with the Python engine', () {
    test(
      'Given the reference corpus, when every chart is redrawn, then the bytes match',
      () async {
        if (!corpusThere || !storeThere) {
          markTestSkipped('reference corpus or store not present');
          return;
        }
        final repository = FolderStoryRepository(
          datasource: YamlFolderDatasource(directory: _store),
        );
        final keys =
            Directory(_store)
                .listSync()
                .whereType<File>()
                .map((f) => f.path.split('/').last)
                .where((name) => name.endsWith('.yaml'))
                .map((name) => name.replaceAll(RegExp(r'\.yaml$'), ''))
                .toList()
              ..sort();

        var identical = 0;
        final failures = <String>[];
        for (final key in keys) {
          final story = (await repository.load(key)).getRight().toNullable();
          if (story == null) continue;
          if (story.shape == StoryShape.twoClock) {
            final file = File('$_reference/twoclock/$key.svg');
            if (!file.existsSync()) continue;
            if (renderTwoClock(story) == file.readAsStringSync()) {
              identical += 1;
            } else {
              failures.add('$key (two-clock)');
            }
            continue;
          }
          for (final (suffix, cb, mini) in const [
            ('', false, false),
            ('.cb', true, false),
            ('.mini', false, true),
          ]) {
            final file = File('$_reference/$key$suffix.svg');
            if (!file.existsSync()) continue;
            final drawn = renderFilmChart(story, cb: cb, mini: mini).svg;
            if (drawn == file.readAsStringSync()) {
              identical += 1;
            } else {
              failures.add('$key$suffix');
            }
          }
        }

        failures.take(8).join(', ').should.be('');
        failures.length.should.be(0);
        // 30 braid films x 3 treatments + 5 two-clock charts
        identical.should.be(95);
      },
    );

    test(
      'Given the drawn layout, when compared with Python, then it matches field for field',
      () async {
        if (!corpusThere || !storeThere) {
          markTestSkipped('reference corpus or store not present');
          return;
        }
        final repository = FolderStoryRepository(
          datasource: YamlFolderDatasource(directory: _store),
        );
        final differences = <String>[];
        for (final entity in Directory(_store).listSync().whereType<File>()) {
          final name = entity.path.split('/').last;
          if (!name.endsWith('.yaml')) continue;
          final key = name.replaceAll(RegExp(r'\.yaml$'), '');
          final specFile = File('$_reference/$key.spec.json');
          if (!specFile.existsSync()) continue;
          final story = (await repository.load(key)).getRight().toNullable();
          if (story == null) continue;
          final expected =
              (jsonDecode(specFile.readAsStringSync())
                      as Map<String, Object?>)['spec']!
                  as Map<String, Object?>;
          final spec = buildChartSpec(story);
          if ((expected['ys']! as List).length != spec.ys.length) {
            differences.add('$key: ys length');
          }
          for (final entry
              in (expected['label_font']! as Map)
                  .cast<String, Object?>()
                  .entries) {
            final want = (entry.value! as num).toDouble();
            if (spec.labelFont[entry.key] != want) {
              differences.add('$key: font ${entry.key}');
            }
          }
          for (final column in spec.columns) {
            if (column.groups.isEmpty && story.beats.isNotEmpty) {
              differences.add('$key: empty groups on "${column.beat}"');
            }
          }
        }
        differences.take(8).join(', ').should.be('');
        differences.length.should.be(0);
      },
    );
  });
}
